baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "Public Safety Data"
theme = "blackburn"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
publishDir="public"
math=true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 3
    identifier = "post"
    url = "/post/"
  [[menu.main]] 
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/dnchelst"
    weight = 4
[params]
    description = "A website built through Hugo and blogdown."
    googleAnalytics = "UA-99039986-1"
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
    DateFormat = "Monday, January 2, 2006"
    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

[social]
  github = "dnchelst"
  linkedin = "dnchelst"
  #kaggle = "dnchelst"
  twitter = "dnchelst"
