## Partial Submissions and Additional Considerations

NFIRS data starts with a specific incident, recorded by an individual
department, and reported to a state agency and/or directly to the federal
government. While quality assurance measures are built into the system, issues
will arise either automatically or inadvertently.
- 
To a degree, NFIRS data submission is voluntary. One who studies this data set 
should understand that it represents information about _most_ but not _all_ 
incidents to which a fire department responded within the U.S. 
Here are three ways that information can be missing:  
1. **Missing Agencies**: An agency's data may not submit its data to NFIRS. 
Alternatively, they may submit their information too late for inclusion in the 
annual data set. For example, the 2015 data set does not include information for
the New Brunswick (NJ) Fire Department.
2. **Missing Records**: Many fire departments respond to medical calls as
emergency first responders. NFIRS can capture this information, but that is not
the system's focus. Some agencies may not report medical calls to NFIRS and
focus only on incidents associated with its primary mission. For example,